<<<<<<< HEAD
# Generated by Django 3.2.8 on 2021-10-17 23:35
=======
# Generated by Django 3.2.8 on 2021-10-13 00:46
>>>>>>> e9f8a83ff2751a9cee1373dfb5eafd8d938c57ce

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
