# Generated by Django 3.2.8 on 2021-10-25 01:04

from django.db import migrations


class Migration(migrations.Migration):



    operations = [
        migrations.DeleteModel(
            name='Oferta',
        ),
    ]
