# Generated by Django 3.2.8 on 2021-12-11 04:01

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_bodega', models.BigIntegerField(primary_key=True, serialize=False)),
                ('num_pasillo', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'bodega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=30, unique=True)),
                ('codigo_postal', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigIntegerField()),
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_paterno', models.CharField(max_length=40)),
                ('apellido_materno', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=1)),
                ('telefono', models.BigIntegerField()),
                ('email', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuentaCliente',
            fields=[
                ('email', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cuenta_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuentaEmpleado',
            fields=[
                ('usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=20)),
                ('rol', models.BigIntegerField()),
            ],
            options={
                'db_table': 'cuenta_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigIntegerField()),
                ('rut', models.CharField(max_length=4000, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_paterno', models.CharField(max_length=40)),
                ('apellido_materno', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=1)),
                ('telefono', models.BigIntegerField()),
                ('email', models.CharField(max_length=40, unique=True)),
                ('cargo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPago',
            fields=[
                ('id_estado_pago', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_estado_pago', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id_estado_pedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_estado_pedido', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id_estado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'estado_solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estanteria',
            fields=[
                ('id_estanteria', models.BigIntegerField(primary_key=True, serialize=False)),
                ('capacidad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'estanteria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_oferta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rut_proveedor', models.CharField(max_length=20)),
                ('nombre_proveedor', models.CharField(max_length=40)),
                ('apellido_proveedor', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('oferta', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'oferta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_orden', models.BigIntegerField(default=core.models.OrdenCompra.number, primary_key=True, serialize=False)),
                ('precio_total', models.BigIntegerField()),
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('fecha_estimada', models.DateField(auto_now=True)),
                ('nombre_comprador', models.CharField(blank=True, max_length=40, null=True)),
                ('apellido_comprador', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'orden_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pasillo',
            fields=[
                ('id_pasillo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('num_estanteria', models.BigIntegerField()),
            ],
            options={
                'db_table': 'pasillo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=30, unique=True)),
                ('precio', models.BigIntegerField()),
                ('stock', models.BigIntegerField()),
                ('oferta', models.CharField(max_length=1)),
                ('porcentaje', models.BigIntegerField(blank=True, null=True)),
                ('imagen', models.BinaryField(blank=True, null=True)),
                ('precio_oferta', models.BigIntegerField(blank=True, null=True)),
                ('valoraciontotal', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudProductos',
            fields=[
                ('id_solicitud', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=30)),
                ('nombre_categoria', models.BigIntegerField()),
                ('precio', models.BigIntegerField()),
                ('nombre_marca', models.BigIntegerField()),
                ('stock', models.BigIntegerField()),
                ('supervisor_rut', models.CharField(max_length=4000)),
                ('bodeguero_rut', models.CharField(max_length=4000)),
                ('observacion', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'solicitud_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoOrden',
            fields=[
                ('id_tipo_orden', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id_tipo_pago', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_pago', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id_valoracion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('valoracion', models.BigIntegerField()),
                ('comentario', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'valoracion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('cantidad', models.BigIntegerField()),
                ('precio', models.BigIntegerField()),
                ('orden_compra_id_orden', models.OneToOneField(db_column='orden_compra_id_orden', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.ordencompra')),
            ],
            options={
                'db_table': 'detalle_orden',
                'managed': False,
            },
        ),
    ]
