# Generated by Django 3.2.8 on 2021-10-09 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_bodega', models.BigIntegerField(primary_key=True, serialize=False)),
                ('num_pasillo', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'bodega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=30)),
                ('codigo_postal', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_paterno', models.CharField(max_length=40)),
                ('apellido_materno', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=1)),
                ('telÚfono', models.BigIntegerField()),
                ('email', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuentaCliente',
            fields=[
                ('email', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cuenta_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuentaEmpleado',
            fields=[
                ('usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cuenta_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id_detalle_orden', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField()),
                ('precio', models.BigIntegerField()),
            ],
            options={
                'db_table': 'detalle_orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigIntegerField()),
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=1)),
                ('telefono', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('cargo', models.BigIntegerField()),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPago',
            fields=[
                ('id_estado_pago', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_estado_pago', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id_estado_pedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_estado_pedido', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estanteria',
            fields=[
                ('id_estanteria', models.BigIntegerField(primary_key=True, serialize=False)),
                ('capacidad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'estanteria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_oferta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_proveedor', models.BigIntegerField()),
                ('nombre_proveedor', models.CharField(max_length=40)),
                ('apellido_proveedor', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('oferta', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'oferta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_orden', models.BigIntegerField(primary_key=True, serialize=False)),
                ('precio_total', models.BigIntegerField()),
                ('fecha_compra', models.DateField()),
                ('fecha_estimada', models.DateField()),
                ('id_tipo_pago', models.BigIntegerField()),
            ],
            options={
                'db_table': 'orden_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pasillo',
            fields=[
                ('id_pasillo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('num_estanteria', models.BigIntegerField()),
            ],
            options={
                'db_table': 'pasillo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=30)),
                ('precio', models.BigIntegerField()),
                ('stock', models.BigIntegerField()),
                ('oferta', models.CharField(max_length=1)),
                ('porcentaje', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudProductos',
            fields=[
                ('id_solicitud', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=30)),
                ('nombre_categoria', models.BigIntegerField()),
                ('precio', models.BigIntegerField()),
                ('nombre_marca', models.BigIntegerField()),
                ('stock', models.BigIntegerField()),
                ('observacion', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'solicitud_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoOrden',
            fields=[
                ('id_tipo_orden', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_orden', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id_tipo_pago', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_pago', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id_valoracion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('valoracion', models.BigIntegerField()),
            ],
            options={
                'db_table': 'valoracion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudPresencial',
            fields=[
                ('id_producto', models.BigIntegerField()),
                ('nombre_producto', models.CharField(max_length=30)),
                ('cantidad', models.BigIntegerField()),
                ('orden_compra_id_orden', models.OneToOneField(db_column='orden_compra_id_orden', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.ordencompra')),
            ],
            options={
                'db_table': 'solicitud_presencial',
                'managed': False,
            },
        ),
    ]
