# Generated by Django 3.2.8 on 2021-10-22 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211021_2056'),
        ('core', '0002_auto_20211021_2111'),
    ]

    operations = [
    ]
