# Generated by Django 3.2.8 on 2021-10-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_0002_auto_20211021_2056_0002_auto_20211021_2111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgenteOferta',
        ),
    ]
