# Generated by Django 3.2.8 on 2021-10-27 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211011_2130'),
        ('core', '0004_auto_20211021_2135'),
        ('core', '0004_delete_agenteoferta'),
    ]

    operations = [
    ]
