# Generated by Django 3.2.8 on 2021-10-31 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211026_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id_estado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'estado_solicitud',
                'managed': False,
            },
        ),
    ]
