# Generated by Django 3.2.6 on 2021-11-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_agenteoferta'),
        ('core', '0007_estadosolicitud'),
    ]

    operations = [
    ]
