# Generated by Django 3.2.8 on 2021-11-26 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_agenteoferta'),
        ('core', '0007_estadosolicitud'),
    ]

    operations = [
    ]
