<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-11-23 00:22
=======
# Generated by Django 3.2.8 on 2021-11-23 00:22
>>>>>>> e8cf305f87cd4b73a5c9035443d27a21ea0189ca

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_agenteoferta'),
        ('core', '0007_estadosolicitud'),
    ]

    operations = [
    ]
