# Generated by Django 3.2.8 on 2021-11-26 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_0004_delete_agenteoferta_0007_estadosolicitud'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
    ]
