# Generated by Django 3.2.6 on 2021-11-30 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211125_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteOferta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'agente_oferta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudPresencial',
            fields=[
                ('id_producto', models.BigIntegerField()),
                ('nombre_producto', models.CharField(max_length=30)),
                ('cantidad', models.BigIntegerField()),
                ('orden_compra_id_orden', models.OneToOneField(db_column='orden_compra_id_orden', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.ordencompra')),
            ],
            options={
                'db_table': 'solicitud_presencial',
                'managed': False,
            },
        ),
    ]
