# Generated by Django 3.2.9 on 2021-12-05 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_authgrouppermissions_authusergroups_authuseruserpermissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
    ]
