# Generated by Django 3.2.8 on 2021-12-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_agenteoferta_authgrouppermissions_authusergroups_authuseruserpermissions_solicitudpresencial'),
        ('core', '0011_auto_20211205_1524'),
    ]

    operations = [
    ]
