# Generated by Django 3.2.6 on 2021-12-09 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20211208_2047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgenteOferta',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='SolicitudPresencial',
        ),
    ]
