# Generated by Django 3.2.8 on 2021-12-11 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211208_2334'),
        ('core', '0014_authgrouppermissions_authusergroups_authuseruserpermissions'),
    ]

    operations = [
    ]
